import React from 'react';

export const About: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto px-4 py-16">
        <div className="bg-white rounded-[3rem] p-8 md:p-16 shadow-lg border border-slate-100">
            <h1 className="font-display text-4xl font-bold text-slate-800 mb-8 text-center">About 10,000 Whys</h1>
            
            <div className="prose prose-lg text-slate-600 mx-auto">
                <p className="lead text-xl text-center mb-10">
                    We believe every "Why?" is an opportunity to learn, but the internet isn't always built for kids. We're changing that.
                </p>

                <h3 className="font-bold text-slate-800 text-2xl mb-4">Our Mission</h3>
                <p className="mb-8">
                    To satisfy the boundless curiosity of children ages 3–9 with simple, accurate answers, verified safe videos, and screen-free activities that bring learning to life.
                </p>

                <h3 className="font-bold text-slate-800 text-2xl mb-4">How We Keep It Safe</h3>
                <ul className="list-disc pl-6 space-y-2 mb-8">
                    <li><strong>Curated Sources:</strong> We only recommend videos from a strict list of verified educational channels like SciShow Kids and Nat Geo.</li>
                    <li><strong>AI + Safety:</strong> Our content is generated by advanced AI specifically instructed to maintain a gentle, kid-friendly tone and avoid sensitive topics.</li>
                    <li><strong>No Ads:</strong> We don't track your kids or sell their attention.</li>
                </ul>

                <h3 className="font-bold text-slate-800 text-2xl mb-4">Off-Screen Focus</h3>
                <p>
                    While we love digital learning, we believe the best lessons happen in the real world. That's why every answer comes with a hands-on activity you can do with household items in under 30 minutes.
                </p>
            </div>
        </div>
    </div>
  );
};